# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true
confirm: true
analyze:
  async: true
  create-group: true
  solc: 0.6.12
  remappings:
    - "@openzeppelin=node_modules/@openzeppelin"
  targets:
    - contracts/bridge/SynapseBridge.sol:SynapseBridge
